dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "codebook",
    "mousemove",
    "mouseup",
    "preact",
    "rustc",
    "todo",
    "vite",
]
flag_words = [
    "todo",
    "fixme",
]
ignore_paths = [
    ".git/**/*",
    "node_modules/**/*",
]
ignore_patterns = ["^[a-zA-Z]{1,3}$"]
use_global = true
